Agenda
- Intro to tensor
- Getting information from tensors
- Manipulating tensors
- Using @tf.function
- Using GPU's with TF
- Exercise

In [2]:
# import Tensorflow
import tensorflow as tf
print(tf.__version__)

2.14.0


In [3]:
# create tensors with tf.constant()
scalar = tf.constant(7) # create a constant tensor from a tensor-like object
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [4]:
scalar.ndim

0

In [5]:
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [6]:
vector.ndim

1

In [7]:
matrix = tf.constant([[10,7],[7,10]])
matrix.ndim

2

In [8]:
mat_1 = tf.constant([[10,4],[23,5],[54,12]],dtype=tf.float16)
mat_1

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  4.],
       [23.,  5.],
       [54., 12.]], dtype=float16)>

In [9]:
mat_1.ndim

2

In [10]:
# 3d tensor
tensor =tf.constant([[[1,2],[3,4]],[[5,6],[7,8]],[[9,10],[11,12]]])
tensor

<tf.Tensor: shape=(3, 2, 2), dtype=int32, numpy=
array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]], dtype=int32)>

In [11]:
tensor.ndim

3

In [12]:
tensor.shape

TensorShape([3, 2, 2])

What we have created
- Scalar: a single number, n=0
- Vector: number with direction
- Matrix: a two-dimenstional array
- Tensor: as n-dim array of numbers

In [13]:
changeable_tensor = tf.Variable([10,7])
unchangeable_variable=tf.constant([11,7])
changeable_tensor,unchangeable_variable

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([11,  7], dtype=int32)>)

In [14]:
changeable_tensor[0]

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [15]:
changeable_tensor[0].assign(15)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([15,  7], dtype=int32)>

In [16]:
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([15,  7], dtype=int32)>

In [17]:
unchangeable_variable[0]

<tf.Tensor: shape=(), dtype=int32, numpy=11>

In [18]:
# unchangeable_variable[0].assign(15)  # wornt work

In [19]:
# random tensors
rand_1=tf.random.Generator.from_seed(10)
rand_1=rand_1.normal(shape=(3,2))
rand_1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.29604465, -0.21134205],
       [ 0.01063002,  1.5165398 ],
       [ 0.27305737, -0.29925638]], dtype=float32)>

In [20]:
rand_1.ndim

2

In [21]:
rand_2=tf.random.uniform(shape=(3,4))
rand_2

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0.32095242, 0.00154531, 0.9293885 , 0.97494125],
       [0.19298363, 0.00455666, 0.59656525, 0.6308975 ],
       [0.41159737, 0.61564565, 0.23910272, 0.8661368 ]], dtype=float32)>

In [22]:
tf.random.set_seed(34)

In [23]:
tf.random.shuffle(rand_2,seed=3)

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0.32095242, 0.00154531, 0.9293885 , 0.97494125],
       [0.19298363, 0.00455666, 0.59656525, 0.6308975 ],
       [0.41159737, 0.61564565, 0.23910272, 0.8661368 ]], dtype=float32)>

In [24]:
tf.ones(shape=(3,5))

<tf.Tensor: shape=(3, 5), dtype=float32, numpy=
array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]], dtype=float32)>

In [25]:
tf.zeros(shape=(4,2))

<tf.Tensor: shape=(4, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]], dtype=float32)>

Turn numpy array into tensors

In [26]:
import numpy as np

In [27]:
x=np.arange(1,25).reshape(4,-1)

In [28]:
y=tf.constant(x)
y

<tf.Tensor: shape=(4, 6), dtype=int64, numpy=
array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])>

In [29]:
x=np.arange(1,25)
z=tf.constant(x,shape=(2,3,4))
z

<tf.Tensor: shape=(2, 3, 4), dtype=int64, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])>

In [40]:
y=tf.zeros(shape=(6,4))

In [45]:
tf.size(z).numpy()

24

In [42]:
z.shape

TensorShape([2, 3, 4])

In [43]:
z.ndim

3

In [44]:
z.dtype

tf.int64

### Indexing
indexing like python

In [48]:
z[:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2), dtype=int64, numpy=
array([[[ 1,  2],
        [ 5,  6]],

       [[13, 14],
        [17, 18]]])>

In [49]:
z[:1,:,:2]

<tf.Tensor: shape=(1, 3, 2), dtype=int64, numpy=
array([[[ 1,  2],
        [ 5,  6],
        [ 9, 10]]])>

### adding new axis

In [52]:
z=z[...,tf.newaxis]  # ... means every axis befor
z.shape

TensorShape([2, 3, 4, 1, 1])

In [53]:
tf.expand_dims(z,axis=-1)
z.shape

TensorShape([2, 3, 4, 1, 1])

In [55]:
z=tf.expand_dims(z,axis=0)
z.shape

TensorShape([1, 2, 3, 4, 1, 1])

In [56]:
z=tf.expand_dims(z,axis=3)
z.shape

TensorShape([1, 2, 3, 1, 4, 1, 1])

### Manipulating tensors

Basic operations

In [57]:
t1=tf.constant(np.random.randint(10,20,size=(2,2)))

In [58]:
t2=tf.constant(np.random.randint(10,20,size=(2,2)))

In [59]:
t1

<tf.Tensor: shape=(2, 2), dtype=int64, numpy=
array([[11, 15],
       [15, 18]])>

In [60]:
t2

<tf.Tensor: shape=(2, 2), dtype=int64, numpy=
array([[16, 12],
       [14, 10]])>

In [61]:
t1+t2

<tf.Tensor: shape=(2, 2), dtype=int64, numpy=
array([[27, 27],
       [29, 28]])>

In [62]:
t1+10

<tf.Tensor: shape=(2, 2), dtype=int64, numpy=
array([[21, 25],
       [25, 28]])>

In [63]:
t1*t2

<tf.Tensor: shape=(2, 2), dtype=int64, numpy=
array([[176, 180],
       [210, 180]])>

In [64]:
t2=tf.Variable(np.random.randint(10,20,size=(2,2)))

In [65]:
t2

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int64, numpy=
array([[16, 12],
       [10, 13]])>

In [66]:
t1*t2

<tf.Tensor: shape=(2, 2), dtype=int64, numpy=
array([[176, 180],
       [150, 234]])>

In [67]:
tf.multiply(t2,t1)

<tf.Tensor: shape=(2, 2), dtype=int64, numpy=
array([[176, 180],
       [150, 234]])>

In [68]:
tf.add(t1,t2)

<tf.Tensor: shape=(2, 2), dtype=int64, numpy=
array([[27, 27],
       [25, 31]])>

### Matrix multiplication

In [72]:
tf.matmul(t1,t2)

<tf.Tensor: shape=(2, 2), dtype=int64, numpy=
array([[326, 327],
       [420, 414]])>

In [79]:
t1@t2

<tf.Tensor: shape=(2, 2), dtype=int64, numpy=
array([[326, 327],
       [420, 414]])>

In [73]:
tf.linalg.matmul(t1,t2)

<tf.Tensor: shape=(2, 2), dtype=int64, numpy=
array([[326, 327],
       [420, 414]])>

In [82]:
tf.tensordot(t1,t2,axes=1)

<tf.Tensor: shape=(2, 2), dtype=int64, numpy=
array([[326, 327],
       [420, 414]])>

### Reshape

In [74]:
t3=tf.constant(np.arange(24).reshape(4,-1))

In [75]:
t3

<tf.Tensor: shape=(4, 6), dtype=int64, numpy=
array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])>

In [77]:
tf.reshape(t3,shape=(6,-1))

<tf.Tensor: shape=(6, 4), dtype=int64, numpy=
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])>

In [80]:
tf.transpose(t3)

<tf.Tensor: shape=(6, 4), dtype=int64, numpy=
array([[ 0,  6, 12, 18],
       [ 1,  7, 13, 19],
       [ 2,  8, 14, 20],
       [ 3,  9, 15, 21],
       [ 4, 10, 16, 22],
       [ 5, 11, 17, 23]])>

### change dtype
16 bit float operation is faster than 32 bit float

In [83]:
t2.dtype

tf.int64

In [84]:
b=tf.cast(t2,dtype=tf.int16)

In [85]:
a=tf.cast(t1,dtype=tf.float16)

In [86]:
a

<tf.Tensor: shape=(2, 2), dtype=float16, numpy=
array([[11., 15.],
       [15., 18.]], dtype=float16)>

### Aggregating Tensors

In [90]:
t4=tf.Variable(np.arange(-5,10).reshape(3,-1))

In [91]:
t4

<tf.Variable 'Variable:0' shape=(3, 5) dtype=int64, numpy=
array([[-5, -4, -3, -2, -1],
       [ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9]])>

In [92]:
tf.abs(t4)

<tf.Tensor: shape=(3, 5), dtype=int64, numpy=
array([[5, 4, 3, 2, 1],
       [0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])>

- Min
- Max
- Mean
- sum

import tensorflow_probability as tfp
- variance
- std

In [95]:
tf.reduce_min(t4).numpy()

-5

In [96]:
tf.reduce_max(t4)

<tf.Tensor: shape=(), dtype=int64, numpy=9>

In [97]:
tf.reduce_mean(t4)

<tf.Tensor: shape=(), dtype=int64, numpy=2>

In [98]:
tf.reduce_sum(t4)

<tf.Tensor: shape=(), dtype=int64, numpy=30>

In [100]:
import tensorflow_probability as tfp

In [112]:
tf.math.reduce_variance(t4)

<tf.Tensor: shape=(), dtype=float32, numpy=18.666666>

In [102]:
tfp.stats.variance(t4)

<tf.Tensor: shape=(5,), dtype=int64, numpy=array([16, 16, 16, 16, 16])>

In [108]:
t4=tf.cast(t4,dtype=tf.float32)

In [109]:
tfp.stats.stddev(t4)

<tf.Tensor: shape=(5,), dtype=float32, numpy=array([4.082483, 4.082483, 4.082483, 4.082483, 4.082483], dtype=float32)>

In [111]:
tf.math.reduce_std(t4)

<tf.Tensor: shape=(), dtype=float32, numpy=4.3204937>

### find positional Max and Min

In [114]:
t3

<tf.Tensor: shape=(4, 6), dtype=int64, numpy=
array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])>

In [121]:
tf.argmax(t3,axis=1)

<tf.Tensor: shape=(4,), dtype=int64, numpy=array([5, 5, 5, 5])>

In [119]:
tf.reduce_max(t3)

<tf.Tensor: shape=(), dtype=int64, numpy=23>

In [125]:
t3[tf.argmin(t3).numpy()[0]]

<tf.Tensor: shape=(6,), dtype=int64, numpy=array([0, 1, 2, 3, 4, 5])>

### squeeze dimension

In [131]:
tf.random.set_seed(23)
t5=tf.constant(tf.random.uniform(shape=[10]),shape=(1,1,10))

In [132]:
t5

<tf.Tensor: shape=(1, 1, 10), dtype=float32, numpy=
array([[[0.43993807, 0.09729016, 0.8235066 , 0.22273934, 0.3318541 ,
         0.25352108, 0.34313524, 0.45672834, 0.60538435, 0.46301937]]],
      dtype=float32)>

In [133]:
t5.shape

TensorShape([1, 1, 10])

In [134]:
t5_squeeze=tf.squeeze(t5)

In [135]:
t5_squeeze.shape

TensorShape([10])

### One hot Encoding

In [139]:
x=[0,1,2,3]
tf.one_hot(x,4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [140]:
tf.one_hot(x,4,on_value='OnV',off_value='OfV')

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'OnV', b'OfV', b'OfV', b'OfV'],
       [b'OfV', b'OnV', b'OfV', b'OfV'],
       [b'OfV', b'OfV', b'OnV', b'OfV'],
       [b'OfV', b'OfV', b'OfV', b'OnV']], dtype=object)>

### squaring, log, Sqrt

In [142]:
t6=tf.range(10)
t6

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [143]:
tf.square(t6)

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [148]:
tf.sqrt(tf.cast(t6,dtype=tf.float32))

<tf.Tensor: shape=(10,), dtype=float32, numpy=
array([0.       , 1.       , 1.4142135, 1.7320508, 2.       , 2.236068 ,
       2.4494898, 2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [152]:
tf.math.log(tf.cast(t6,dtype=tf.float64))

<tf.Tensor: shape=(10,), dtype=float64, numpy=
array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])>

### Tensors and Numpy

Tensorflow interacts beautifully with Numpy array
Tensorflow built upon tensor and Numpy built upon array. full interoperatbility



In [153]:
t7=tf.constant(np.array([2,4,5]))

In [154]:
np.array(t7)

array([2, 4, 5])

In [155]:
type(np.array(t7))

numpy.ndarray

In [156]:
t7.numpy()

array([2, 4, 5])

In [157]:
t8=tf.constant(np.array([3.,5.]))
t9=tf.constant([3.,5.])
t8.dtype,t9.dtype

(tf.float64, tf.float32)

# Neural Network

## Regression Problem/ predicting a number
- How much this house will seel for
- How many people will buy
- How much health insurance will be
- etc...
- prediction of the location of an object in an image

## Agenda
- Architecture of NN regression model
- Input shapes and output shapes of a regression model
- Creating custom data to view and fit
- Steps in modelling
  - Creating a model, compiling a model, fitting a model,evaluating a model
- Different evaluation methods
- Saving and loading models

most of the time we will be focused on defining input and outputs and their shapes.   
![HyperParameter](https://drive.google.com/file/d/1Ykz9RM7wf9NFhWiMlm4YL72n7WyPn_U8/view?usp=sharing)

![HyperParameter2](https://drive.google.com/file/d/1ENmwt-xzWN_rgyOU2zmN1wqORJUqWDpA/view?usp=sharing)